# Generated by Django 5.2.1 on 2025-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailywalletstart_walletstartbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refill',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='refill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='refill',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='refill_amount_non_negative'),
        ),
    ]
